import { ICedulaBase } from "@/schemas/cedulas/GetCedula";

export function normalizarCedulas(data: ICedulaBase[]): ICedulaBase[] {
  return data.map((cedula) => ({
    idCedula: cedula.idCedula || 0,
    analista: cedula.analista || "",
    antecedentesFamiliaresUV: cedula.antecedentesFamiliaresUV || "",
    aprobadoDireccion: false,
    aprobadoJefeOficina: false,
    archivoAdjunto: false,
    categoriaPuestoOrigen: cedula.categoriaPuestoOrigen || "",
    competenciaDesarrollar: cedula.competenciaDesarrollar || "",
    competenciaReforzar: cedula.competenciaReforzar || "",
    competenciasSobresaliente: cedula.competenciasSobresaliente || "",
    conclusiones: cedula.conclusiones || "",
    consecutivoExpediente: cedula.consecutivoExpediente || "",
    dependencia: cedula.dependencia || "",
    descripcionDesarrollar: cedula.descripcionDesarrollar || "",
    descripcionReforzar: cedula.descripcionReforzar || "",
    diasProceso: cedula.diasProceso || "",
    edad: cedula.edad || "",
    educacionFormal: Array.isArray(cedula.educacionFormal)
      ? cedula.educacionFormal.find((e) => e) || ""
      : cedula.educacionFormal || "",
    efectoContratacion: cedula.efectoContratacion || "",
    estado: cedula.estado || false,
    evaluacionConocimientos: cedula.evaluacionConocimientos || "",
    expectativaLaboral: cedula.expectativaLaboral || "",
    experiencia: cedula.experiencia || "",
    experienciaLaboralSolicitada: cedula.experienciaLaboralSolicitada || "",
    experienciaRelacionada: cedula.experienciaRelacionada || "",
    familiaFuncional: cedula.familiaFuncional || "",
    fechaCedulaInterna: cedula.fechaCedulaInterna || "",
    fechaCedulaResultados: cedula.fechaCedulaResultados || "",
    fechaElaboracionPropuesta: cedula.fechaElaboracionPropuesta || "",
    fechaEntrevista: cedula.fechaEntrevista || "",
    fechaEnvioDEyDP: cedula.fechaEnvioDEyDP || "",
    fechaEnvioEvaluacionDesempenio: cedula.fechaEnvioEvaluacionDesempenio || "",
    fechaEvaluacionCompetencias: cedula.fechaEvaluacionCompetencias || "",
    fechaEvaluacionDesempenio: cedula.fechaEnvioEvaluacionDesempenio || "",
    fechaInicioProcesamiento: cedula.fechaInicioProcesamiento || "",
    fechaLiberacionOficio: cedula.fechaLiberacionOficio || "",
    fechaNotificacion: cedula.fechaNotificacion || "",
    fechaRecibido: cedula.fechaRecibido || "",
    fechaRevisionOfiEval: cedula.fechaRevisionOfiEval || "",
    FKIdClasificacionCedula: cedula.FKIdClasificacionCedula || 0,
    FKIdProceso: cedula.FKIdResultado || 0,
    FKIdResultado: cedula.FKIdResultado || 0,
    FKIdTipoCedula: cedula.FKIdTipoCedula === 1 ? 1 : 2,
    folio: cedula.folio || "",
    funcionDesempeniar: cedula.funcionDesempeniar || "",
    hermesNotificacion: cedula.hermesNotificacion || "",
    lineamientoOficioContinuidad: cedula.lineamientoOficioContinuidad || "",
    motivo: cedula.motivo || "",
    motivoCedulaInterna: cedula.motivoCedulaInterna || "",
    motivoCedulaResultados: cedula.motivoCedulaResultados || "",
    nombreCandidato: cedula.nombreCandidato || "N/A",
    numCarpeta: cedula.numCarpeta || "",
    numPlaza: cedula.numPlaza || "",
    observaciones: cedula.observaciones || "",
    observacionesAnalista: cedula.observacionesAnalista || "",
    oficioAutorizacionDeOcupacion: cedula.oficioAutorizacionDeOcupacion || "",
    periodoAutorizadoOficioFin: cedula.periodoAutorizadoOficioFin || "",
    periodoAutorizadoOficioInicio: cedula.periodoAutorizadoOficioInicio || "",
    plaza: cedula.plaza || "",
    puesto: cedula.puesto || "N/A",
    psicometriaAnalisisProblemas: cedula.psicometriaAnalisisProblemas || "",
    psicometriaComunicacion: cedula.psicometriaComunicacion || "",
    psicometriaControlActividades: cedula.psicometriaControlActividades || "",
    psicometriaDinamismo: cedula.psicometriaDinamismo || "",
    psicometriaEnfoqueCalidad: cedula.psicometriaEnfoqueCalidad || "",
    psicometriaEnfoqueResultados: cedula.psicometriaEnfoqueCalidad || "",
    psicometriaInnovacion: cedula.psicometriaInnovacion || "",
    psicometriaLiderazgo: cedula.psicometriaLiderazgo || "",
    psicometriaNegociacion: cedula.psicometriaNegociacion || "",
    psicometriaOrientacionAlServicio:
      cedula.psicometriaOrientacionAlServicio || "",
    psicometriaPensamientoEstrategico:
      cedula.psicometriaPensamientoEstrategico || "",
    psicometriaPlaneacionOrganizacion:
      cedula.psicometriaPlaneacionOrganizacion || "",
    psicometriaRelacionesInterpersonales:
      cedula.psicometriaRelacionesInterpersonales || "",
    psicometriaSensibilidadALineamientos:
      cedula.psicometriaSensibilidadALineamientos || "",
    psicometriaTomaDecisiones: cedula.psicometriaTomaDecisiones || "",
    psicometriaTrabajoEnEquipo: cedula.psicometriaTrabajoEnEquipo || "",
    referidoPor: cedula.referidoPor || "",
    resultado: cedula.resultado || "Pendiente",
    resultadoEvaluacionCompetencias:
      cedula.resultadoEvaluacionCompetencias || "",
    resultadoEvaluacionConocimiento:
      cedula.resultadoEvaluacionConocimiento || "",
    resultadoHabilidadesExcel: cedula.resultadoHabilidadesExcel || "N/A",
    resultadoHabilidadesWord: cedula.resultadoHabilidadesWord || "",
    resultadoOrtografia: cedula.resultadoOrtografia || "",
    resultadoPorcentaje: cedula.resultadoPorcentaje || "",
    resultadoProcesoEvaluacion: cedula.resultadoProcesoEvaluacion || "",
    resultadoReferenciasLaborales: cedula.resultadoReferenciasLaborales || "",
    resultadoSeguimientoEvaluacionDesempenio:
      cedula.resultadoSeguimientoEvaluacionDesempenio || "",
    seguimientoEvaluacionDesempenio:
      cedula.seguimientoEvaluacionDesempenio || "",
    titularPlaza: cedula.titularPlaza || "",
  }));
}
/**
 * FKIdTipoCedula: cedula.FKIdTipoCedula === 1 ? "Interna" : "Resultados",
 * educacionFormal
 * dependencia: c.nombreDependencia || "N/A",
 */
