import { ICedulaNormalizada } from "@/interfaces/cedulas/CedulaNormalizada";
import { ICedulaRaw } from "@/interfaces/cedulas/CedulaRaw";

export function normalizarCedulas(data: ICedulaRaw[]): ICedulaNormalizada[] {
  return data.map((c) => ({
    idCedula: c.idCedula,
    folio: c.folio || "",
    hermesNotificacion: c.hermesNotificacion || "",
    candidato: c.nombreCandidato || "N/A",
    dependencia: c.nombreDependencia || "N/A",
    puesto: c.puesto || "N/A",
    resultado: c.resultado || "Pendiente",
    cedula: c.FKIdTipoCedula === 1 ? "Interna" : "Resultados",
    estado: c.estado || false,
    idProceso: c.idProceso,
    numeroPlaza: c.numPlaza,
    referidoPor: c.referidoPor,
    antecedentesFamiliaresUV: c.antecedentesFamiliaresUV,
    resultadoHabilidadesWord: c.resultadoHabilidadesWord,
    resultadoOrtografia: c.resultadoOrtografia,
    resultadoHabilidadesExcelReal: c.resultadoHabilidadesExcel,
    resultadoEvaluacionConocimiento: c.resultadoEvaluacionConocimiento,
    expectativaLaboral: c.expectativaLaboral,
    experiencia: c.experiencia,
    conclusiones: c.conclusiones,
    FKIdClasificacionCedula: c.FKIdClasificacionCedula,
    fechaElaboracionCedulaInterna: c.fechaCedulaInterna,
    psicometriaComunicacion: c.psicometriaComunicacion,
    psicometriaTrabajoEnEquipo: c.psicometriaTrabajoEnEquipo,
    psicometriaOrientacionAlServicio: c.psicometriaOrientacionAlServicio,
    psicometriaSensibilidadALineamientos:
      c.psicometriaSensibilidadALineamientos,
    psicometriaPlaneacionOrganizacion: c.psicometriaPlaneacionOrganizacion,
    psicometriaAnalisisProblemas: c.psicometriaAnalisisProblemas,
    psicometriaEnfoqueResultados: c.psicometriaEnfoqueResultados,
    psicometriaControlActividades: c.psicometriaControlActividades,
    psicometriaEnfoqueCalidad: c.psicometriaEnfoqueCalidad,
    psicometriaRelacionesInterpersonales:
      c.psicometriaRelacionesInterpersonales,
    psicometriaLiderazgo: c.psicometriaLiderazgo,
    psicometriaTomaDecisiones: c.psicometriaTomaDecisiones,
    psicometriaDinamismo: c.psicometriaDinamismo,
    psicometriaInnovacion: c.psicometriaInnovacion,
    psicometriaPensamientoEstrategico: c.psicometriaPensamientoEstrategico,
    psicometriaNegociacion: c.psicometriaNegociacion,
    analista: c.analista,
    resultadoHabilidadesExcel: c.resultadoHabilidadesExcel || "N/A",
    avaladoPor: c.avaladoPor,
    FKIdTipoCedula: c.FKIdTipoCedula,
    FKIdTipoProceso: c.FKIdTipoProceso,
    idDependencia: c.FKIdDependencia,
    edad: c.edad,
    plaza: c.plaza,
    oficioAutorizacionDeOcupacion: c.oficioAutorizacionDeOcupacion,
    educacionFormal: Array.isArray(c.educacionFormal)
      ? c.educacionFormal.find((e) => e) || ""
      : c.educacionFormal || "",
    experienciaRelacionada: c.experienciaRelacionada,
    competenciaReforzar: c.competenciaReforzar,
    competenciaDesarrollar: c.competenciaDesarrollar,
    competenciasSobresaliente: c.competenciasSobresaliente,
    evaluacionConocimientos: c.evaluacionConocimientos,
    efectoContratacion: c.efectoContratacion,
    descripcionReforzar: c.descripcionReforzar,
    descripcionDesarrollar: c.descripcionDesarrollar,
    titularPlaza: c.titularPlaza,
    resultadoProcesoEvaluacion: c.resultadoProcesoEvaluacion,
    FKIdTemporalDefinitiva: c.FKIdTemporalDefinitiva,
    aprobadoJefeOficina: c.aprobadoJefeOficina,
    aprobadoDireccion: c.aprobadoDireccion,
  }));
}
