export interface IPostProcesoContratacion {
	autorizacion: boolean;
	beneficiado: boolean;
	categoriaAutorizadaOficio: string;
	categoriaPuestoOrigen: string;
	consecutivoExpediente: string;
	diasProceso: string;
	experienciaLaboralSolicitada: string;
	familiaFuncional: string;
	fechaElaboracionPropuesta: string;
	fechaEntrevista: string;
	fechaEnvioDEyDP: string;
	fechaEnvioEvaluacionDesempenio: string;
	fechaEvaluacionCompetencias: string;
	fechaInicioProcesamiento: string;
	fechaLiberacionOficio: string;
	fechaNotificacion: string;
	fechaRecibido: string;
	fechaRevisionOfiEval: string;
	folio: string;
	FKIdAcceso: number;
	FKIdDependencia: number;
	FKIdEstadoProcesoContratacion: number;
	FKIdTemporalDefinitiva: number;
	FKIdTipoPersonal: number;
	FKIdTipoProceso: number;
	funcionDesempeniar: string;
	hermesNotificacion: string;
	lineamientoOficioContinuidad: string;
	motivo: string;
	nombreCandidato: string;
	numCarpeta: string;
	numPlaza: string;
	observaciones: string;
	observacionesAnalista: string;
	periodoAutorizadoOficioFin: string;
	periodoAutorizadoOficioInicio: string;
	resultadoEvaluacionCompetencias: string;
	resultadoEvaluacionConocimiento: string;
	resultadoHabilidadesExcel: string;
	resultadoHabilidadesWord: string;
	resultadoOrtografia: string;
	resultadoProcesoEvaluacion: string;
	resultadoReferenciasLaborales: string;
	resultadoSeguimientoEvaluacionDesempenio: string;
	titularPlaza: string;
}

export type ISolicitudAsignacionRequisicion = Pick<
	IPostProcesoContratacion,
	| "autorizacion"
	| "categoriaAutorizadaOficio"
	| "categoriaPuestoOrigen"
	| "FKIdAcceso"
	| "FKIdDependencia"
	| "FKIdEstadoProcesoContratacion"
	| "FKIdTemporalDefinitiva"
	| "FKIdTipoPersonal"
	| "FKIdTipoProceso"
	| "funcionDesempeniar"
	| "hermesNotificacion"
	| "lineamientoOficioContinuidad"
	| "motivo"
	| "nombreCandidato"
	| "numPlaza"
	| "observaciones"
	| "periodoAutorizadoOficioFin"
	| "periodoAutorizadoOficioInicio"
	| "resultadoEvaluacionCompetencias"
	| "resultadoEvaluacionConocimiento"
	| "resultadoHabilidadesExcel"
	| "resultadoHabilidadesWord"
	| "resultadoOrtografia"
	| "resultadoProcesoEvaluacion"
	| "resultadoReferenciasLaborales"
	| "resultadoSeguimientoEvaluacionDesempenio"
	| "titularPlaza"
>;

export type ISolicitudBolsaTrabajo = Pick<
	IPostProcesoContratacion,
	| "autorizacion"
	| "beneficiado"
	| "categoriaAutorizadaOficio"
	| "categoriaPuestoOrigen"
	| "consecutivoExpediente"
	| "diasProceso"
	| "experienciaLaboralSolicitada"
	| "familiaFuncional"
	| "fechaElaboracionPropuesta"
	| "fechaEntrevista"
	| "fechaEnvioDEyDP"
	| "fechaEvaluacionCompetencias"
	| "fechaInicioProcesamiento"
	| "fechaLiberacionOficio"
	| "fechaNotificacion"
	| "fechaRecibido"
	| "fechaRevisionOfiEval"
	| "folio"
	| "FKIdAcceso"
	| "FKIdDependencia"
	| "FKIdEstadoProcesoContratacion"
	| "FKIdTemporalDefinitiva"
	| "FKIdTipoPersonal"
	| "FKIdTipoProceso"
	| "funcionDesempeniar"
	| "hermesNotificacion"
	| "lineamientoOficioContinuidad"
	| "motivo"
	| "nombreCandidato"
	| "numCarpeta"
	| "numPlaza"
	| "observaciones"
	| "observacionesAnalista"
	| "periodoAutorizadoOficioFin"
	| "periodoAutorizadoOficioInicio"
	| "resultadoEvaluacionConocimiento"
	| "resultadoReferenciasLaborales"
	| "resultadoSeguimientoEvaluacionDesempenio"
	| "titularPlaza"
>;
